MiyoshiTaishou/MS2024

- MS2024/Assets/Resource/ScriptableObject.meta
- MS2024/Assets/Resource/ScriptableObject/SampleInfo.asset
- MS2024/Assets/Resource/ScriptableObject/SampleInfo.asset.meta
- MS2024/Assets/Resource/ScriptableObject/TestScene_MiyoshiInfo.asset
- MS2024/Assets/Resource/ScriptableObject/TestScene_MiyoshiInfo.asset.meta
- MS2024/Assets/Scenes/Miyoshi.meta
- MS2024/Assets/Scenes/Miyoshi/TestScene_Miyoshi.meta
- MS2024/Assets/Scenes/Miyoshi/TestScene_Miyoshi.unity
- MS2024/Assets/Scenes/Miyoshi/TestScene_Miyoshi.unity.meta
- MS2024/Assets/Scenes/Miyoshi/TestScene_Miyoshi/GlobalVolumeProfile.asset
- MS2024/Assets/Scenes/Miyoshi/TestScene_Miyoshi/GlobalVolumeProfile.asset.meta
- MS2024/Assets/Script/Scene.meta
- MS2024/Assets/Script/Scene/BaseSceneManager.cs
- MS2024/Assets/Script/Scene/BaseSceneManager.cs.meta
- MS2024/Assets/Script/Scene/CanavsFadeSceneLoad.cs
- MS2024/Assets/Script/Scene/CanavsFadeSceneLoad.cs.meta
- MS2024/Assets/Script/Scene/SceneInfoObject.cs
- MS2024/Assets/Script/Scene/SceneInfoObject.cs.meta
- MS2024/ProjectSettings/EditorBuildSettings.asset
シーン遷移に必要そうな情報をまとめた
ScriptableObjectを実装
キャンバスを使ったフェード処理実装
> シーン遷移ベース処理

- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Common.pdb.meta
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Realtime.pdb.meta
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Runtime.pdb.meta
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Sockets.pdb.meta
- MS2024/Assets/Photon/FusionDemos/Photon-Fusion-Intro-Sample-2.0.2-Stable-851.unitypackage.meta
- MS2024/Assets/Photon/FusionMenu/Photon-Fusion-Menu-2.0.2-Stable-851.unitypackage.meta
- MS2024/Assets/Photon/PhotonLibs/netstandard2.0/Photon3Unity3D.pdb.meta
- MS2024/Assets/Scenes/Miyoshi/NetStayRoom.unity
- MS2024/Assets/Script/Scene/SceneSelecter.cs
- MS2024/Assets/Script/Scene/SceneSelecter.cs.meta
> SelectScene

- MS2024/Assets/Scenes/Miyoshi/NetTestScene_Miyoshi.unity
- MS2024/Assets/Script/Camera/CinemaCharCamera.cs
- MS2024/Assets/Script/Camera/CinemaCharCamera.cs.meta
- MS2024/Assets/Script/NetWork/BasicSpawner.cs
カメラ追従
揺らす処理（まだテストしてない）
ズーム処理（まだテストしてない）
> キャラ追従カメラその他機能追加

- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Common.pdb.meta
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Realtime.pdb.meta
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Runtime.pdb.meta
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Sockets.pdb.meta
- MS2024/Assets/Photon/FusionDemos/Photon-Fusion-Intro-Sample-2.0.2-Stable-851.unitypackage.meta
- MS2024/Assets/Photon/FusionMenu/Photon-Fusion-Menu-2.0.2-Stable-851.unitypackage.meta
- MS2024/Assets/Photon/PhotonLibs/netstandard2.0/Photon3Unity3D.pdb.meta
- MS2024/Assets/Script/NetWork/NetWorkStat.cs
- MS2024/Assets/Script/NetWork/NetWorkStat.cs.meta
- MS2024/Assets/Script/NetWork/NetworkStatManager.cs
- MS2024/Assets/Script/NetWork/NetworkStatManager.cs.meta
同期処理を行うクラスの作成
同期する値を管理するマネージャー作成
> 同期処理ベースクラスとマネージャー

- MS2024/Assets/Editor/PlayerStateEditor.cs
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Common.pdb.meta
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Realtime.pdb.meta
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Runtime.pdb.meta
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Sockets.pdb.meta
- MS2024/Assets/Photon/FusionDemos/Photon-Fusion-Intro-Sample-2.0.2-Stable-851.unitypackage.meta
- MS2024/Assets/Photon/FusionMenu/Photon-Fusion-Menu-2.0.2-Stable-851.unitypackage.meta
- MS2024/Assets/Photon/PhotonLibs/netstandard2.0/Photon3Unity3D.pdb.meta
- MS2024/Assets/Resource/InputSystem/Player.inputactions
- MS2024/Assets/Resource/Model/Character/Player2D.prefab
- MS2024/Assets/Scenes/Miyoshi/LocalPlayerScene.unity
- MS2024/Assets/Script/Character/PlayerState/PlayerIdleState.cs
- MS2024/Assets/Script/Character/PlayerState/PlayerJumpState.cs
- MS2024/Assets/Script/Character/PlayerState/PlayerJumpState.cs.meta
- MS2024/Assets/Script/Character/PlayerState/PlayerState.cs
- MS2024/ProjectSettings/TagManager.asset
> プレイヤーの移動、ジャンプ

- MS2024/Assets/Resource/Animation.meta
- MS2024/Assets/Resource/Animation/ACPlayer.controller
- MS2024/Assets/Resource/Animation/ACPlayer.controller.meta
- MS2024/Assets/Resource/Animation/APlayerIdle.anim
- MS2024/Assets/Resource/Animation/APlayerIdle.anim.meta
- MS2024/Assets/Resource/Animation/APlayerWalk.anim
- MS2024/Assets/Resource/Animation/APlayerWalk.anim.meta
- MS2024/Assets/Resource/Model/Character/Player2D.prefab
- MS2024/Assets/Script/Character/PlayerState/PlayerIdleState.cs
- MS2024/Assets/Script/Character/PlayerState/PlayerMoveState.cs
- MS2024/Assets/Script/Character/PlayerState/PlayerState.cs
歩行と待機アニメーション作成
アニメーション切り替えシステム作成
> Playerアニメーション

- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Common.pdb.meta
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Sockets.pdb.meta
- MS2024/Assets/Photon/FusionMenu/Photon-Fusion-Menu-2.0.2-Stable-851.unitypackage.meta
- MS2024/Assets/Photon/PhotonLibs/netstandard2.0/Photon3Unity3D.pdb.meta
- MS2024/Assets/Resource/Animation/ACPlayer.controller
- MS2024/Assets/Resource/Animation/APlayerAtack.anim
- MS2024/Assets/Resource/Animation/APlayerAtack.anim.meta
- MS2024/Assets/Scenes/Okamoto.meta
- MS2024/Assets/Scenes/Okamoto/Okamoto_AnimaTest.unity
- MS2024/Assets/Scenes/Okamoto/Okamoto_AnimaTest.unity.meta
> 試しに攻撃モーションの追加

- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Common.pdb.meta
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Realtime.pdb.meta
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Runtime.pdb.meta
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Sockets.pdb.meta
- MS2024/Assets/Photon/FusionDemos/Photon-Fusion-Intro-Sample-2.0.2-Stable-851.unitypackage.meta
- MS2024/Assets/Photon/FusionMenu/Photon-Fusion-Menu-2.0.2-Stable-851.unitypackage.meta
- MS2024/Assets/Photon/PhotonLibs/netstandard2.0/Photon3Unity3D.pdb.meta
- MS2024/Assets/Resource/Animation/APlayerJump.anim
- MS2024/Assets/Resource/Animation/APlayerJump.anim.meta
- MS2024/Assets/Resource/Animation/APlayerLand.anim
- MS2024/Assets/Resource/Animation/APlayerLand.anim.meta
- MS2024/Assets/Script/Character/PlayerState/PlayerIdleState.cs
- MS2024/Assets/Script/Character/PlayerState/PlayerJumpState.cs
- MS2024/Assets/Script/Character/PlayerState/PlayerMoveState.cs
- MS2024/Assets/Script/Character/PlayerState/PlayerState.cs
着地のタイミングに合わせるアニメーションを作成
移動時にキャラの向きを変えた
> ジャンプアニメーションとキャラの向き

- MS2024/Assets/Scenes/Matsuki/NetTestScene_Matsuki.unity
- MS2024/Assets/Script/Enemy/Boss_Bard/Boss Animation.controller
移動キー同時押しすると先に入力した方のアニメーション優先します
> 移動アニメーション追加

- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Common.pdb.meta
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Realtime.pdb.meta
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Runtime.pdb.meta
- MS2024/Assets/Photon/Fusion/Assemblies/Fusion.Sockets.pdb.meta
- MS2024/Assets/Photon/FusionDemos/Photon-Fusion-Intro-Sample-2.0.2-Stable-851.unitypackage.meta
- MS2024/Assets/Photon/FusionMenu/Photon-Fusion-Menu-2.0.2-Stable-851.unitypackage.meta
- MS2024/Assets/Photon/PhotonLibs/netstandard2.0/Photon3Unity3D.pdb.meta
- MS2024/Assets/Scenes/main.unity
> ボス配置とカメラエラー対応

- MS2024/Assets/InputSystem.inputsettings.asset
- MS2024/Assets/InputSystem.inputsettings.asset.meta
- MS2024/Assets/Resource/Model/Character/Player2D.prefab
- MS2024/Assets/Scenes/Matsuki/NetTestScene_Matsuki.unity
- MS2024/Assets/Script/Enemy/Boss_Bard/BossEnemy.cs
- MS2024/Assets/uketori.unity
- MS2024/Assets/uketori.unity.meta
- MS2024/Assets/watasi.unity
- MS2024/Assets/watasi.unity.meta
> Bossダメージリアクション

- MS2024/Assets/Resource/Model/Enemy/BasicMotions_DummyModel.prefab
- MS2024/Assets/Resource/Model/Enemy/BasicMotions_DummyModel.prefab.meta
- MS2024/ProjectSettings/EditorBuildSettings.asset
> Boss(仮)prefab追加

- MS2025/Assets/Prefab/Boss2D.prefab
- MS2025/Assets/Prefab/Boss2D.prefab.meta
- MS2025/Assets/Resource/ScriptableObject/BossActionList.asset
- MS2025/Assets/Resource/ScriptableObject/BossActionList.asset.meta
- MS2025/Assets/Resource/ScriptableObject/BossAttackData.asset
- MS2025/Assets/Resource/ScriptableObject/BossAttackData.asset.meta
- MS2025/Assets/Resource/ScriptableObject/MoveAction.asset
- MS2025/Assets/Resource/ScriptableObject/MoveAction.asset.meta
- MS2025/Assets/Scenes/Miyoshi/MargeScene_Miyoshi.unity
- MS2025/Assets/Scenes/Miyoshi/Title_Network.unity
- MS2025/Assets/Script/Enemy/BossAI.cs
- MS2025/Assets/Script/Enemy/BossActionData.cs
- MS2025/Assets/Script/Enemy/BossActionData.cs.meta
- MS2025/Assets/Script/Enemy/BossActionSequence.cs
- MS2025/Assets/Script/Enemy/BossActionSequence.cs.meta
- MS2025/Assets/Script/Enemy/BossAttackAction.cs
- MS2025/Assets/Script/Enemy/BossAttackAction.cs.meta
- MS2025/Assets/Script/Enemy/BossIdleAction.cs
- MS2025/Assets/Script/Enemy/BossIdleAction.cs.meta
- MS2025/Assets/Script/Enemy/BossMoveAction.cs
- MS2025/Assets/Script/Enemy/BossMoveAction.cs.meta
- MS2025/Assets/Script/Network/GameLauncher.cs
簡易版移動と攻撃（DebugLogのみ）実装
行動を上から順番に行う形で実装プランナーが行動を管理しやすいようにしている
> BossAIシステム実装

- MS2025/Assets/Prefab/Boss2D.prefab
- MS2025/Assets/Resource/ScriptableObject/BossAttackData 1.asset
- MS2025/Assets/Resource/ScriptableObject/BossAttackData.asset
- MS2025/Assets/Resource/ScriptableObject/JumpAction.asset
- MS2025/Assets/Resource/ScriptableObject/JumpAction.asset.meta
- MS2025/Assets/Resource/ScriptableObject/TestActionSequence.asset
- MS2025/Assets/Resource/ScriptableObject/TestActionSequence.asset.meta
- MS2025/Assets/Script/Enemy/BossAttackAction.cs
- MS2025/Assets/Script/Enemy/BossJumpAction.cs
- MS2025/Assets/Script/Enemy/BossJumpAction.cs.meta
- MS2025/ProjectSettings/EditorBuildSettings.asset
> Jumpアクション実装

- MS2025/Assets/Resource/Object/Field/Main Camera.prefab
- MS2025/Assets/Resource/Object/Field/Main Camera.prefab.meta
- MS2025/Assets/Resource/ScriptableObject/BossAttackData 2.asset
- MS2025/Assets/Scenes/Miyoshi/MargeScene_Miyoshi.unity
- MS2025/Assets/Script/Camera/CameraShake.cs
- MS2025/Assets/Script/Camera/CameraShake.cs.meta
- MS2025/Assets/Script/Enemy/BossAI.cs
- MS2025/Assets/Script/Enemy/BossAttackAction.cs
- MS2025/Assets/Script/Enemy/BossJumpAction.cs
ジャンプ中の判定を実装してかちあげでダウンするかどうか判断できるようにした
ボスの衝撃波が大技の割にはしょぼいからカメラ揺らしてみた
ネットワークまだ未検証
> ボスがジャンプ中かどうかの判定と衝撃波でカメラが揺れる

- MS2025/Assets/Resource/ScriptableObject/TutorialBossData.meta
- MS2025/Assets/Resource/ScriptableObject/TutorialBossData/BASTutorial1.asset
- MS2025/Assets/Resource/ScriptableObject/TutorialBossData/BASTutorial1.asset.meta
- MS2025/Assets/Resource/ScriptableObject/TutorialBossData/BASTutorial2.asset
- MS2025/Assets/Resource/ScriptableObject/TutorialBossData/BASTutorial2.asset.meta
- MS2025/Assets/Resource/ScriptableObject/TutorialBossData/TutorialWaitAction.asset
- MS2025/Assets/Resource/ScriptableObject/TutorialBossData/TutorialWaitAction.asset.meta
- MS2025/Assets/Resource/UI/TitleCanvas.prefab
- MS2025/Assets/Scenes/Miyoshi/Title_Network.unity
- MS2025/Assets/Scenes/Miyoshi/TutorialScene_Miyoshi.meta
- MS2025/Assets/Scenes/Miyoshi/TutorialScene_Miyoshi.unity
- MS2025/Assets/Scenes/Miyoshi/TutorialScene_Miyoshi.unity.meta
- MS2025/Assets/Scenes/Miyoshi/TutorialScene_Miyoshi/GlobalVolumeProfile.asset
- MS2025/Assets/Scenes/Miyoshi/TutorialScene_Miyoshi/GlobalVolumeProfile.asset.meta
- MS2025/Assets/Script/Object/ChangeBossAction.cs
- MS2025/Assets/Script/Object/ChangeBossAction.cs.meta
- MS2025/ProjectSettings/EditorBuildSettings.asset
案山子状態と定期的に攻撃する状態をゲーム中に好きに切り替えれる
> チュートリアルシーンの作成とボスの行動データを作成

- MS2025/Assets/Scenes/Miyoshi/TutorialScene_Miyoshi.unity
- MS2025/Assets/Script/Scene/StayLoadScene.cs
- MS2025/Assets/Script/UI/TransitionManager.cs
> チュートリアル画面遷移処理

- MS2025/Assets/Resource/UI/MainGameUI.prefab
- MS2025/Assets/Scenes/Build/MargeScene_Build.unity
- MS2025/Assets/Script/Player/ComboSystem.cs
- MS2025/Assets/Script/Player/PlayerChargeAttack.cs
- MS2025/Assets/Script/benri/NumberChange.cs
Reverts MiyoshiTaishou/MS2024#714
> Revert "コンボ数カウントネット対応とチャージエフェクトバグ修正"

- MS2025/Assets/Prefab/Player.prefab
- MS2025/Assets/Script/Character/Network/PlayerJumpNet.cs
- MS2025/Assets/Script/Object/PlayerMove.cs
> 溜め攻撃と連携攻撃のヒットストップ実装

- MS2025/Assets/Resource/ScriptableObject/TutorialBossData/BASTutorial1.asset
- MS2025/Assets/Resource/ScriptableObject/TutorialBossData/TutorialMoveAttack.asset
- MS2025/Assets/Resource/ScriptableObject/TutorialBossData/TutorialMoveAttack.asset.meta
- MS2025/Assets/Scenes/Miyoshi/Title_Network.unity
- MS2025/Assets/Scenes/Miyoshi/TutorialScene_Miyoshi.unity
- MS2025/Assets/Script/Boss/BossAttackArea.cs
- MS2025/Assets/Script/Enemy/BossActionMoveAttack.cs
- MS2025/Assets/Script/Enemy/BossActionMoveAttack.cs.meta
> ロケットパンチ処理実装

- MS2025/Assets/Prefab/Player.prefab
- MS2025/Assets/Prefab/Sound/SoundManager.prefab
- MS2025/Assets/Resource/Animation/Enemy/JumpAttack.anim
- MS2025/Assets/Resource/Animation/Enemy/Mizunomidori2D.controller
- MS2025/Assets/Resource/ScriptableObject/DownAction.asset
- MS2025/Assets/Resource/ScriptableObject/Planner/O_ActionSequence 2.asset
- MS2025/Assets/Scenes/Build/MargeScene_Build.unity
- MS2025/Assets/Scenes/Build/Title_Network_Build.unity
ボスのアニメーションでおかしなところの調整とプレイヤーのステータスをかちあげ攻撃をしやすい程度に調整しました。ステージ配置の方は森君と話あってもう少しサイズ調整や行灯（光源）の配置をした方が良いと判断したので、見送って追加で作業して頂く事にしました。
> 動画/テストプレイ用の調整完了

- MS2025/Assets/Resource/Animation/Enemy/Mizunomidori/wark 1.anim
アニメーションのアニメーションに抜けがあったので調整し直しました
> 水飲み鳥の歩きアニメーション

- MS2025/Assets/Resource/ScriptableObject/Boss2/Boss2D3Attack2 1.asset
- MS2025/Assets/Resource/ScriptableObject/Boss2/Boss2D3Attack2 1.asset.meta
- MS2025/Assets/Resource/ScriptableObject/Boss2/Boss2D3Attack2.asset
- MS2025/Assets/Resource/ScriptableObject/Boss2/Boss2D3Attack2.asset.meta
- MS2025/Assets/Resource/ScriptableObject/Boss2/Boss2DDoubleAttack.asset
- MS2025/Assets/Resource/ScriptableObject/Boss2/RoundAction 1.asset
- MS2025/Assets/Resource/ScriptableObject/Boss2/RoundAction 1.asset.meta
- MS2025/Assets/Resource/ScriptableObject/Boss2/RoundAction.asset
- MS2025/Assets/Resource/ScriptableObject/Boss2/RoundAction.asset.meta
- MS2025/Assets/Scenes/Miyoshi/Boss2Stage.unity
- MS2025/Assets/Script/Enemy/BossMoveRoundAction.cs
- MS2025/Assets/Script/Enemy/BossMoveRoundAction.cs.meta
ぐるぐる外周をまわりながら遠距離攻撃していくような形で作成中
> 2ボス行動データ作成途中

- MS2025/Assets/Prefab/Player.prefab
- MS2025/Assets/Script/Player/PlayerChargeAttack.cs
> チャージ攻撃のエフェクト追加

- MS2025/Assets/Resource/Animation/Enemy/Mizunomidori/Jump.anim
- MS2025/Assets/Resource/Animation/Enemy/Mizunomidori/wark 1.anim
- MS2025/Assets/Resource/ScriptableObject/Planner/Attack/K_BossAttackData Under50.asset
- MS2025/Assets/Resource/ScriptableObject/Planner/K_JumpAction.asset
- MS2025/Assets/Scenes/Build/MargeScene_Build.unity
・HPを極端に低くしてみました。
・ボスの歩行アニメーション修正。
・ボスのジャンプアニメーション修正。
・５０％の時の攻撃速度修正
> ボスのアニメーション修正、弱体化調整

- MS2025/Assets/Scenes/Okamoto/MargeScene_OkamotoMk2.unity
- MS2025/Assets/Scenes/Okamoto/MargeScene_OkamotoMk2.unity.meta
- MS2025/Assets/Scenes/Okamoto/Title_Network_OkamotoMk2.unity
- MS2025/Assets/Scenes/Okamoto/Title_Network_OkamotoMk2.unity.meta
背景の壁の影がステージにかかっていて見ずらい印象でしたので、影を消しておきました。
それに伴って行灯を再配置しました。
> ステージの影と明るさ

- MS2025/Assets/Script/Character/2D/PlayerParryNet.cs
- MS2025/Assets/Script/Player/AttackAreaDamage.cs
- MS2025/Assets/Script/Player/ChargeAttackAreaDamage.cs
- MS2025/Assets/Script/Player/ComboSystem.cs
パリィが一回受けるとオートで発動するバグ修正、コンボUIが出なくなるバグ修正
> チャージ攻撃を空中でくらってもボスがのけぞろらないように変更、バグ修正

- MS2025/Assets/Scenes/Build/Title_Network_Build.unity
- MS2025/Assets/Scenes/Build/TutorialScene_Build.unity
- MS2025/Assets/Scenes/Build/TutorialScene_Build.unity.meta
- MS2025/ProjectSettings/EditorBuildSettings.asset
> チュートリアルのコピーシーン作成作業途中

- MS2025/Assets/Resource/Animation/Enemy/Boss2/body/Boss2D.controller
- MS2025/Assets/Resource/Animation/Enemy/Boss2/body/knockback.anim
- MS2025/Assets/Resource/Animation/SpecialAttack/Enemy/SpecialAttackEnemy.controller
- MS2025/Assets/Resource/TimeLine/TLSpecialAttackOkamoto 1.playable
- MS2025/Assets/Scenes/Miyoshi/Boss2Stage.unity
Reverts MiyoshiTaishou/MS2024#1254
> Revert "2ボス必殺技演出/エフェクト差替え/HPバー削除"

- MS2025/Assets/Scenes/Miyoshi/Boss2Stage.unity
クライアント側のゲームオーバーUIにズレがあったので修正しました。
> 2ボスのゲームオーバーUI修正

- MS2025/Assets/Scenes/Build/MargeScene_Build.unity
Reverts MiyoshiTaishou/MS2024#1343
> Revert "修正の修正"

- MS2025/Assets/Scenes/Build/Title_Network_Build.unity
- MS2025/Assets/Scenes/Build/TutorialScene_Build.unity
- MS2025/Assets/Scenes/Miyoshi/Boss2Stage.unity
Reverts MiyoshiTaishou/MS2024#1339
> Revert "アシュラマン怒り"
